name: Build
on:
    workflow_run:
    workflows: ["Test"]
    types:
        - completed
        - success
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build