# name: Test CI/CD mother fucker
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#   release:
#     types:
#       - published
#   schedule:
#     - cron: '0 0 * * 0'
