name: main
on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Deploy
        run: echo "Deploying to production..."

  # Send discord message
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "deploy success Bitch ! https://tenor.com/view/rosycheeks-approved-i-approve-well-done-good-job-gif-16996150"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
