name: Test
on:
    workflow_run:
    workflows: ["Test"]
    types:
        - completed
        - success
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: npm run test
